[tool.poetry]
name = "yanotes/api"
version = "1.0.0"
description = "API for yet another note-taking app"
authors = ["Eduard Malokhvii <malokhvii.ee@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.10"
Django = "^4.1"
django-admin-interface = "^0.20.0"
django-environ = "^0.9.0"
django-filter = "^22.1"
django-structlog = "^3.0.1"
djangorestframework = "^3.13.1"
djangorestframework-simplejwt = "^5.2.0"
drf-spectacular = {extras = ["sidecar"], version = "^0.23.1"}
psycopg2-binary = "^2.9.3"
django-cors-headers = "^3.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py310"]
experimental_string_processing = true

[tool.isort]
py_version = 310
profile = "black"
lines_between_types = 1
lines_after_imports = 2
